@host = http://localhost:3000

### Create a New User
POST {{host}}/api/users
Content-Type: application/json

{
  "name": "Malcolm Nigel",
  "email": "nkomo@example.com",
  "password": "secuw3passwo1d",
  "role": "seller"
}

### Get All Users
GET {{host}}/api/users

### Get Single User by ID
GET {{host}}/api/users/68810b23f4937423b6320df9

---

### Create a New Product
POST {{host}}/api/products
Content-Type: application/json

{
  "name": "WANTAM Wooden Bowl",
  "price": 1800,
  "description": "Locally crafted from mahogany",
  "image": "/images/wooden-bowl.jpg",
  "category": "Kitchenware",
  "stock": 50
}

### Get All Products
GET {{host}}/api/products

### Get Product by ID
GET {{host}}/api/products/68810a19f4937423b6320df5

### Update Product by ID
PUT {{host}}/api/products/68810a19f4937423b6320df5
Content-Type: application/json

{
  "name": "Updated Handmade Wooden Bowl",
  "price": 2000,
  "stock": 100
}

### Delete Product by ID
DELETE {{host}}/api/products/688251acbcfaf8e46960cac0

---

### Add Items to Cart
POST {{host}}/api/cart
Content-Type: application/json

{
  "userId": "68810b23f4937423b6320df9",
  "items": [
    {
      "productId": "68834dfcca2adc4dd5f949b3",
      "quantity": 3
    }
  ]
}

### Get User Cart
GET {{host}}/api/cart/6883607869a043ea60307da5

### Update User Cart
PUT {{host}}/api/cart/6883607869a043ea60307da5
Content-Type: application/json

{
  "items": [
    {
      "productId": "68834dfcca2adc4dd5f949b3",
      "quantity": 5
    }
  ]
}

### Delete User Cart
DELETE {{host}}/api/cart/6883607869a043ea60307da5

---

### Create Order
POST {{host}}/api/orders
Content-Type: application/json

{
  "userId": "68810b23f4937423b6320df9",
  "products": [
    {
      "productId": "68834dfcca2adc4dd5f949b3",
      "quantity": 5
    }
  ],
  "total": 36990
}

### Get All Orders
GET {{host}}/api/orders

### Get Orders by User ID
GET {{host}}/api/orders/user/68810b23f4937423b6320df9

### Get Single Order by ID
GET {{host}}/api/orders/68810ed97587348ead8914b9

### Delete an Order
DELETE {{host}}/api/orders/688364d569a043ea60307dd6
